sudo: false

language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - cmake
    - gcc-4.8
    - g++-4.8
    - cppcheck
#    - clang

compiler:
  - gcc
#  - clang

os:
  - linux
  - osx

env:
  - BUILD_TYPE=Debug ANALYZE=false
  - BUILD_TYPE=Release ANALYZE=false
#  - BUILD_TYPE=Debug ANALYZE=true
#  - TEST_DIR=140/labs
#  - TEST_DIR=140/labs/lab2

notifications:
  email:
    on_success: never
    on_failure: never

cache: apt

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - BUILD_DIR=$PWD/builds
  - mkdir -p ${BUILD_DIR}
  - cd ${BUILD_DIR}
  - sh ../.travis.sh
#  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
#  - cmake -DCMAKE_BUILD_TYPE=Debug ../$TEST_DIR
#  - cd ${BUILD_DIR}
#  - make

before_script:
  # verify installed versions
  - which cmake
  - cmake --version
  - which g++
  - g++ -v
  - which g++-4.8
  - g++-4.8 -v
#  - which clang
#  - clang -v
#  - ls -l
#  - ls -l bin/
#  - ls -l bin/140/
#  - ls -l lab2/
#  - ls -l lab1/

script:
  # build and test
#  - cd ${BUILD_DIR}/${TEST_DIR} # doesn't work...
  - if [ $ANALYZE = "false" ]; then ctest --timeout 120 -V; fi
#  - ctest --timeout 120 -V

# deploy:
#   provider: releases
#   api-key: "GITHUB OAUTH TOKEN"
#   file:
#     - "FILE 1"
#     - "FILE 2"
#   skip_cleanup: true
#   on:
#     tags: true
